name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.11.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=3.29.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "1.0.8"
  provider: "6.1.2"
  video_player: "2.9.5"
  wakelock_plus: "1.2.10"
  async: "2.12.0"
  media_kit: "1.2.0"
  media_kit_video: "1.3.0"
  media_kit_libs_video: "1.0.6"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
